#ifndef OOP_PROJECT_BUYABLEDISPLAYEDTYPE_H
#define OOP_PROJECT_BUYABLEDISPLAYEDTYPE_H

enum class BuyableDisplayedType{
    ALL,
    PRODUCT,
    CLOTHING,
    SERVICE
};

#endif // OOP_PROJECT_BUYABLEDISPLAYEDTYPE_H
